// Downloads the app's webfonts into public/fonts and writes a local
// @font-face stylesheet. Self-hosting keeps the typography intact when the
// installed app launches offline — a Google Fonts <link> would not.
// Run with `npm run fonts` (only needed when the font list changes).
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const outDir = resolve(root, "src/fonts");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,600;1,500&family=IBM+Plex+Mono:wght@400;500;600&family=Inter:wght@400;500;600&display=swap";

// A desktop UA is what makes Google serve woff2 rather than legacy formats.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const css = await fetch(CSS_URL, { headers: { "User-Agent": UA } }).then((r) => {
  if (!r.ok) throw new Error(`font css: ${r.status}`);
  return r.text();
});

// The stylesheet ships every unicode subset. This app is English-only, so
// only the latin blocks are kept — the rest would triple the precache.
const blocks = css
  .split("/*")
  .map((chunk) => `/*${chunk}`)
  .filter((chunk) => /^\/\*\s*latin\s*\*\//.test(chunk) && chunk.includes("@font-face"));

if (blocks.length === 0) throw new Error("no latin @font-face blocks found");

mkdirSync(outDir, { recursive: true });

let out = "/* Generated by scripts/fetch-fonts.js — do not edit by hand. */\n";

for (const block of blocks) {
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
  if (!url || !family || !weight) continue;

  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${style}.woff2`;
  const bytes = Buffer.from(
    await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
      if (!r.ok) throw new Error(`${name}: ${r.status}`);
      return r.arrayBuffer();
    })
  );
  writeFileSync(resolve(outDir, name), bytes);
  console.log(`wrote src/fonts/${name} (${(bytes.length / 1024).toFixed(1)} kB)`);

  out +=
    `\n@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: ${style};\n` +
    `  font-weight: ${weight};\n` +
    `  font-display: swap;\n` +
    // Relative so Vite fingerprints the file and applies the deploy base.
    `  src: url('./fonts/${name}') format('woff2');\n` +
    `}\n`;
}

writeFileSync(resolve(root, "src/fonts.css"), out);
console.log("wrote src/fonts.css");
